############# English menu ##############

[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Services"
url = "/services/"
weight = 2

[[main]]
name = "About"
url = "/about/"
weight = 3

[[main]]
name = "Contact"
url = "/contact/"
weight = 4

[[main]]
name = "RU"
url = "/"
weight = 9

[[footer]]
name = "Services"
url = "/services/"
weight = 1

[[footer]]
name = "About"
url = "/about/"
weight = 2

[[footer]]
name = "Contact"
url = "/contact/"
weight = 3
